git:
  autoForwardBranches: none
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
notARepository: skip
promptToReturnFromSubprocess: false
theme:
  lightTheme: false
